"""empty message

Revision ID: 321f2c6cad8c
Revises: 
Create Date: 2020-11-29 00:37:46.125267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321f2c6cad8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('Temp1d4', sa.Float(), nullable=True),
    sa.Column('Temp2d5', sa.Float(), nullable=True),
    sa.Column('Temp3d6', sa.Float(), nullable=True),
    sa.Column('Temp4d13', sa.Float(), nullable=True),
    sa.Column('Temp5d19', sa.Float(), nullable=True),
    sa.Column('Temp6d26', sa.Float(), nullable=True),
    sa.Column('Temp7d21', sa.Float(), nullable=True),
    sa.Column('Temp8d20', sa.Float(), nullable=True),
    sa.Column('Temp9d16', sa.Float(), nullable=True),
    sa.Column('Temp10d12', sa.Float(), nullable=True),
    sa.Column('Temp11d1', sa.Float(), nullable=True),
    sa.Column('Temp12d7', sa.Float(), nullable=True),
    sa.Column('Temp13d8', sa.Float(), nullable=True),
    sa.Column('Temp14d24', sa.Float(), nullable=True),
    sa.Column('Temp15d23', sa.Float(), nullable=True),
    sa.Column('Temp16d18', sa.Float(), nullable=True),
    sa.Column('Temp17d15', sa.Float(), nullable=True),
    sa.Column('Temp18d14', sa.Float(), nullable=True),
    sa.Column('Temp19d2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    # ### end Alembic commands ###
